[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "npm ci --only=production",
  "npm run build"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "npm start"
